spring:
  application:
    name: content-service
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_SERVER_HOST}:${DB_SERVER_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 0
      initialization-fail-timeout: -1
      connection-timeout: 3000
      validation-timeout: 1000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/postgres/changelog-master.yaml
    enabled: false
  sql:
    init:
      continue-on-error: true
  jackson:
    default-property-inclusion: non_null

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  health:
    db:
      enabled: false