spring:
  application:
    name: content-service
  datasource:
    username: ${PSQL_DB_USERNAME}
    password: ${PSQL_DB_PASSWORD}
    url: jdbc:postgresql://${PSQL_SERVER_HOST}:${PSQL_SERVER_PORT}/${PSQL_DB_NAME}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 0
      initialization-fail-timeout: -1
      connection-timeout: 3000
      validation-timeout: 1000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/postgres/changelog-master.yaml
    enabled: false
  sql:
    init:
      continue-on-error: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  health:
    db:
      enabled: false